# Generated by Django 2.2.3 on 2019-09-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
