# Generated by Django 2.2.3 on 2019-09-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_person_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
