# Generated by Django 2.2.3 on 2019-09-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190924_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='people',
            field=models.ManyToManyField(to='events.Person'),
        ),
    ]
