# Generated by Django 2.2.3 on 2019-09-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190924_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='notes',
            field=models.TextField(default='RANDOM NOTE!'),
            preserve_default=False,
        ),
    ]
