# Generated by Django 2.2.3 on 2019-10-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20191015_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
        migrations.AlterField(
            model_name='networking',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='networking',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
