# Generated by Django 2.2.3 on 2019-09-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=10)),
                ('institution', models.CharField(default='McMaster University', max_length=50)),
                ('tutorial_1_start', models.DateTimeField(blank=True, null=True)),
                ('tutorial_1_end', models.DateTimeField(blank=True, null=True)),
                ('tutorial_2_start', models.DateTimeField(blank=True, null=True)),
                ('tutorial_2_end', models.DateTimeField(blank=True, null=True)),
                ('lecture_1_start', models.DateTimeField(blank=True, null=True)),
                ('lecture_1_end', models.DateTimeField(blank=True, null=True)),
                ('lecture_2_start', models.DateTimeField(blank=True, null=True)),
                ('lecture_2_end', models.DateTimeField(blank=True, null=True)),
                ('lecture_3_start', models.DateTimeField(blank=True, null=True)),
                ('lecture_3_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
