# Generated by Django 2.2.3 on 2019-09-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='final_exam',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='midterm1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='midterm2',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
