# Generated by Django 2.2.3 on 2019-10-15 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
