# Generated by Django 2.2.3 on 2019-10-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_auto_20191008_2029'),
        ('events', '0008_auto_20191015_1719'),
        ('Calendar', '0003_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Tasks.Assignment')),
                ('coding_challenge', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Tasks.CodingChallenge')),
                ('daily_task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Tasks.DailyTask')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Tasks.Exam')),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='events.Interview')),
                ('networking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='events.Networking')),
                ('other', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Tasks.Other')),
            ],
        ),
    ]
