# Generated by Django 2.2.3 on 2019-10-18 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0004_calendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Tasks.Assignment'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='coding_challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Tasks.CodingChallenge'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='daily_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Tasks.DailyTask'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='exam',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Tasks.Exam'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='interview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.Interview'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='networking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.Networking'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='other',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Tasks.Other'),
        ),
    ]
