# Generated by Django 2.2.3 on 2019-10-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0005_auto_20191018_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
    ]
