# Generated by Django 2.2.3 on 2019-10-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0006_delete_calendarevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
