# Generated by Django 2.2.3 on 2019-09-30 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0002_auto_20190930_1719'),
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='other',
            old_name='notest',
            new_name='notes',
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_by', models.DateTimeField()),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Classes.Course')),
            ],
        ),
    ]
