# Generated by Django 2.2.3 on 2019-10-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_auto_20191004_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='name',
            field=models.CharField(default='TempName', max_length=100),
            preserve_default=False,
        ),
    ]
