# Generated by Django 2.2.3 on 2019-10-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_assignment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='name',
            field=models.CharField(default='NAME', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='other',
            name='name',
            field=models.CharField(default='NAME', max_length=80),
            preserve_default=False,
        ),
    ]
