# Generated by Django 2.2.3 on 2019-10-20 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_auto_20191008_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingchallenge',
            name='allowed_time',
        ),
    ]
